name: ft-transcendence

services:
  # main proxy service
  proxy:
    image: nginx:stable
    networks:
      - transcendence
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - proxy_ssl_secret
      - proxy_ssl_pub
    ports:
      - 80:80
      - 443:443
    restart: always

  # frontend service
  frontend:
    image: nginx:stable
    networks:
      - transcendence
    volumes:
      - ../ft_transcendence-frontend:/usr/share/nginx/html:ro
    restart: always

  # authentication services
  db-auth:
    image: postgres:latest
    networks:
      - transcendence
    env_file:
      - ./env/db-auth.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_auth_pw
    secrets:
      - db_auth_pw
    volumes:
      - db_auth:/var/lib/postgresql/data:rw
    restart: always

  # authentication services
  be-auth:
    build: ../ft_transcendence-be-auth
    env_file:
      - ./env/be-auth.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_auth_pw
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      OAUTH_UID_FILE: /run/secrets/oauth_uid
      OAUTH_SECRET_FILE: /run/secrets/oauth_secret
    secrets:
      - db_auth_pw
      - django_secret
      - jwt_secret
      - oauth_uid
      - oauth_secret
    networks:
      - transcendence
    depends_on:
      - db-auth
      - proxy
    restart: always

  # chatting services
  db-chat:
    image: postgres:latest
    networks:
      - transcendence
    env_file:
      - ./env/db-chat.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_chat_pw
    secrets:
      - db_chat_pw
    restart: always

  # chatting services
  be-chat:
    build: ../ft_transcendence-be-chat
    env_file:
      - ./env/be-chat.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_chat_pw
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - db_chat_pw
      - django_secret
      - jwt_secret
    networks:
      - transcendence
    depends_on:
      - db-chat
      - proxy
    restart: always

  # game services
  db-game:
    image: postgres:latest
    networks:
      - transcendence
    env_file:
      - ./env/db-game.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_game_pw
    secrets:
      - db_game_pw
    restart: always

  # game services
  be-game:
    build: ../ft_transcendence-be-game
    env_file:
      - ./env/be-game.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_game_pw
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - db_game_pw
      - django_secret
      - jwt_secret
    networks:
      - transcendence
    volumes:
      - db_auth:/var/lib/postgresql/data:rw
    depends_on:
      - proxy
    restart: always

networks:
  transcendence:


volumes:
  db_auth:
  db_game:


secrets:
  db_auth_pw:
    file: ./env/db-auth-secret.env
  db_chat_pw:
    file: ./env/db-chat-secret.env
  db_game_pw:
    file: ./env/db-game-secret.env
  django_secret:
    file: ./env/django-secret.env
  jwt_secret:
    file: ./env/jwt-secret.env
  oauth_uid:
    file: ./env/oauth-uid.env
  oauth_secret:
    file: ./env/oauth-secret.env
  proxy_ssl_secret:
    file: ./proxy/ssl.key
  proxy_ssl_pub:
    file: ./proxy/ssl.crt
