name: ft-transcendence

services:
  db-auth:
    image: postgres:latest
    networks:
      - transcendence
    env_file:
      - ./env/db-auth.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_auth_pw
    secrets:
      - db_auth_pw
    volumes:
      - db_auth:/var/lib/postgresql/data:rw
    restart: always

  proxy:
    image: nginx:stable
    networks:
      - transcendence
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - proxy_ssl_secret
      - proxy_ssl_pub
    ports:
      - 80:80
      - 443:443
    restart: always

  frontend:
    image: nginx:stable
    networks:
      - transcendence
    volumes:
      - ../ft_transcendence-frontend:/usr/share/nginx/html:ro
    restart: always

  be-auth:
    build: ../ft_transcendence-be-auth
    env_file:
      - ./env/be-auth.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_auth_pw
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      OAUTH_UID_FILE: /run/secrets/oauth_uid
      OAUTH_SECRET_FILE: /run/secrets/oauth_secret
    secrets:
      - db_auth_pw
      - django_secret
      - jwt_secret
      - oauth_uid
      - oauth_secret
    networks:
      - transcendence
    # TODO pass db connection info, 42 intra OAuth key, jwt key
    depends_on:
      - db-auth
      - proxy
    restart: always

  # be-chat:
  #   build: ../ft_transcendence-be-chat
  #   networks:
  #     - transcendence
  #   # TODO pass db connection info, 42 intra OAuth key, jwt key
  #   depends_on:
  #     - proxy
  #   restart: always

  # be-game:
  #   build: ../ft_transcendence-be-game
  #   networks:
  #     - transcendence
  #   # TODO pass db connection info, 42 intra OAuth key, jwt key
  #   depends_on:
  #     - proxy
  #   restart: always

networks:
  transcendence:


volumes:
  db_auth:


secrets:
  db_auth_pw:
    file: ./env/db-auth-secret.env
  django_secret:
    file: ./env/django-secret.env
  jwt_secret:
    file: ./env/jwt-secret.env
  oauth_uid:
    file: ./env/oauth-uid.env
  oauth_secret:
    file: ./env/oauth-secret.env
  proxy_ssl_secret:
    file: ./proxy/ssl.key
  proxy_ssl_pub:
    file: ./proxy/ssl.crt
